'use client';

// import { Link } from 'next/link';
import { useRouter } from 'next/navigation';
import './globals.css';

export const metadata = {
  title: 'Exploring Next JS 13',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const router = useRouter();

  return (
    <html lang="en">
      <body>
        <nav class="bg-gray-900 shadow">
          <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
              <div class="flex-shrink-0">
                <a onClick={() => router.push('/')} class="text-white text-2xl font-bold cursor-pointer">My Site</a>
              </div>
              <div class="hidden md:block">
                <div class="ml-10 flex items-baseline space-x-4">

                  <button class="text-gray-300 transition-all hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" onClick={() => router.push('/services')}>Services</button>

                  <button class="text-gray-300 transition-all hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" onClick={() => router.push('/contact')}>Contact</button>
                  {/* <Link href="/services" class="text-gray-300 transition-all hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Services</Link>

                  <Link href="/contact" class="text-gray-300 transition-all hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Contact</Link> */}
                </div>
              </div>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
